config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {sessions: 'admins/sessions', registrations: 'admins/registrations'}
  devise_for :students, controllers: { sessions: 'students/sessions'}, skip: :registrations
  resources :enrollments do
    resources :quarters, except: %i[index]
  end 
  resources :courses
  resources :students
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/quarter.rb
class Quarter < ApplicationRecord
  # Relations
  belongs_to :enrollment

  # Validations
  validates :quarter_number, presence: true
  validates :quarter_number, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 4
  }
  validates :grade, presence: true
  validates :grade, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 10
  }
  validates_uniqueness_of :quarter_number, {scope: :enrollment_id, message: "already has a grade"}

  def passed?
    grade > 5
  end
end

app/controllers/quarters_controller.rb
class QuartersController < ApplicationController
  before_action :verify_admin
  before_action :set_enrollment, only: %i[new create edit update]
  before_action :set_quarter, only: %i[edit update destroy]

  def index
  end

  def new
    @quarter = Quarter.new
  end

  def create
    @quarter = @enrollment.quarters.new(quarter_params)

    respond_to do |format|
      if @quarter.save
        QuarterMailer.with(quarter: @quarter).new_grade.deliver_later
        format.html { redirect_to enrollment_url(@enrollment), notice: "quarter was successfully created." }
        format.json { render :show, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quarter.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end
  
  def update
    respond_to do |format|
      if @quarter.update(quarter_params)
        QuarterMailer.with(quarter: @quarter).update_grade.deliver_later
        format.html { redirect_to enrollment_url(@enrollment), notice: "quarter was successfully updated." }
        format.json { render :show, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quarter.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
  end

  private
  def set_enrollment
    @enrollment = Enrollment.find(params[:enrollment_id])
  end
  def set_quarter
    @quarter = Quarter.find_by(id: params[:id], enrollment_id: params[:enrollment_id])
  end
  def quarter_params
    params.require(:quarter).permit(:grade, :quarter_number)
  end
end

app/views/quarters/_form.html.erb
<%= form_with(model: quarter, url: [enrollment, quarter], class: "pure-form pure-form-stacked") do |form| %>
  <% if quarter.errors.any? %>
    <div style="color: red">
      <h4><%= pluralize(quarter.errors.count, "error") %> prohibited this quarter from being saved:</h4>

      <ul>
        <% quarter.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <%= form.label "Select quarter number*", style: "display: block" %>
    <%= form.select :quarter_number,
      options_for_select(
        (1..4).collect{|quarter| [quarter, quarter]},
        { selected: quarter.quarter_number }
      )
    %>

    <%= form.label "Grade*", style: "display: block" %>
    <%= form.select :grade,
      options_for_select(
        (1..10).collect{|grade| [grade, grade]},
        { selected: quarter.grade }
      )
    %>

    <span class="pure-form-message">* Required fields</span>
    <%= form.submit "Send", class: "pure-button pure-button-primary" %>
  </fieldset>
<% end %>

app/views/quarters/edit.html.erb
<h1>Update Grade to Enrollment</h1>

<%= render "form", quarter: @quarter, enrollment: @enrollment %>

<%= link_to "Back to enrollment", enrollment_path(@enrollment), class: "pure-button button-cancel" %>

app/views/quarters/new.html.erb
<h1>Add Grade to Enrollment</h1>

<%= render "form", quarter: @quarter, enrollment: @enrollment %>

<%= link_to "Back to enrollment", enrollment_path(@enrollment), class: "pure-button button-cancel" %>