config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {sessions: 'admins/sessions', registrations: 'admins/registrations'}
  devise_for :students, controllers: { sessions: 'students/sessions'}, skip: :registrations
  resources :enrollments do
    resources :quarters, except: %i[index]
  end 
  resources :courses
  resources :students
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  # Relations
  has_many :enrollments
  has_many :courses, through: :enrollments

  # Validations
  validates :fullname, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true

  # Scopes
  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }
end

app/controllers/students/sessions_controller.rb
# frozen_string_literal: true

class Students::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :verify_not_admin_login

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  private
  def verify_not_admin_login
    redirect_to(root_url, alert: "Already logged in as Admin!") if current_admin
  end
  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]
  before_action :verify_admin, except: %i[ show edit update ]
  before_action :verify_authentication, only: %i[ show edit update ]
  before_action :verify_same_student, only: %i[ show edit update ]
  before_action :allow_without_password, only: %i[ update ]

  # GET /students or /students.json
  def index
    @students = Student.active
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    temporal_password = Devise.friendly_token.first(8)
    @student = Student.new(student_params)
    @student.password = temporal_password

    respond_to do |format|
      if @student.save
        StudentMailer.with(student: @student, temporal_password: temporal_password).welcome_email.deliver_later
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_update_params)
        bypass_sign_in(@student)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.update(active: false)

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully deactivated." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:fullname, :email)
    end

    def student_update_params
      params.require(:student).permit(:fullname, :email, :password, :password_confirmation)
    end

    def verify_same_student
      if current_student
        redirect_to(enrollments_path, alert: "You cannot access to different student information.") unless current_student.id == @student.id
      end
    end

    def allow_without_password
      if params[:student][:password].blank? && params[:student][:password_confirmation].blank?
          params[:student].delete(:password)
          params[:student].delete(:password_confirmation)
      end
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student, class: "pure-form pure-form-stacked") do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h4><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h4>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <%= form.label :fullname, style: "display: block" %>
    <%= form.text_field :fullname %>

    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>

    <%- if current_student %>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>

    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.password_field :password_confirmation %>
    <%- end %>

    <%= form.submit "Send", class: "pure-button pure-button-primary" %>
  </fieldset>
<% end %>

app/views/students/_student-table.html.erb
<tr id="<%= dom_id student %>">
  <td>
    <%= student.fullname %>
  </td>

  <td>
    <%= student.email %>
  </td>
  <td>
    <%= link_to "See student details", student, class: "pure-button" %>
  </td>
</tr>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>Fullname:</strong>
    <%= student.fullname %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= student.email %>
  </p>

</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path, class: "pure-button"  %>
</div>

app/views/students/index.html.erb
<h1>Students</h1>

<div id="students">
  <table class="pure-table pure-table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Actions</th>
      </tr>
    </thead>
  <% @students.each do |student| %>
    <%= render 'student-table', student: student %>
  <% end %>
  </table>
</div>

<%= link_to "New student", new_student_path, class: "pure-button button-secondary" %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path, class: "pure-button button-cancel" %>
</div>

app/views/students/show.html.erb
<%= render @student %>

<div>
  <%= link_to "Edit student", edit_student_path(@student), class: "pure-button pure-button-primary" %> |
  <%- if current_student %>
  <%= link_to "Back to enrollments", enrollments_path, class: "pure-button button-cancel" %>
  <%-end %>
  <%- if current_admin %>
  <%= link_to "Back to students", students_path, class: "pure-button button-cancel" %>

  <%= button_to "Deactivate student this student", @student, method: :delete, class: "pure-button button-error", data: { turbo_confirm: "Are you sure?" } %>
  <%- end %>
</div>