config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {sessions: 'admins/sessions', registrations: 'admins/registrations'}
  devise_for :students, controllers: { sessions: 'students/sessions'}, skip: :registrations
  resources :enrollments do
    resources :quarters, except: %i[index]
  end 
  resources :courses
  resources :students
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/views/shared/_alert.html.erb
<p style="color: red"><%= alert %></p>

app/views/shared/_links.html.erb
<hr />
<div class="pure-g">
  <%- if controller_name != 'sessions' %>
    <%= link_to "Log in", new_session_path(resource_name), class: 'pure-button button-secondary' %>
  <% end %>

  <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
    <%= link_to "Sign up", new_registration_path(resource_name), class: 'pure-button button-secondary' %>
  <% end %>

  <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <%= link_to "Forgot your password?", new_password_path(resource_name), class: "pure-button" %>
  <% end %>

  <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %>
  <% end %>

  <%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %>
  <% end %>

  <%- if devise_mapping.omniauthable? %>
    <%- resource_class.omniauth_providers.each do |provider| %>
      <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %>
    <% end %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav>
  <div class="nav-wrapper">
    <div class="nav-links">
      <ul>
        <%- if current_student || current_admin %>
        <li><%= link_to "Enrollments", enrollments_path %></li>
        <%- end %>
        <%- if current_admin %>
        <li><%= link_to "Courses", courses_path %></li>
        <li><%= link_to "Students", students_path %></li>
        <%- end %>
      </ul>
    </div>
    <div class="nav-login-links">
      <ul>
        <%- if current_admin || current_student %>
        <li><%= link_to "Edit my info", current_admin ? edit_admin_registration_path : student_path(current_student), class: "pure-button button-secondary" %></li>
        <li><%= button_to "Sign out", current_admin ? destroy_admin_session_path : destroy_student_session_path, method: :delete, class: "pure-button button-error", data: {turbo_confirm: "Are you sure to sign out?"} %></li>
        <%- else %>
        <li><%= link_to "Log in as Admin", new_admin_session_path, class: "pure-button pure-button-primary" %></li>
        <li><%= link_to "Log in as Student", new_student_session_path, class: "pure-button button-secondary" %></li>
        <%- end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_notice.html.erb
<p style="color: green"><%= notice %></p>