config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {sessions: 'admins/sessions', registrations: 'admins/registrations'}
  devise_for :students, controllers: { sessions: 'students/sessions'}, skip: :registrations
  resources :enrollments do
    resources :quarters, except: %i[index]
  end 
  resources :courses
  resources :students
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  # Relations
  belongs_to :course
  belongs_to :student
  has_many :quarters, dependent: :delete_all

  # Validations
  validates :course_id, presence: true
  validates :student_id, presence: true
  validates :year, presence: true
  validates :year, numericality: {
    only_integer: true, 
    greater_than_or_equal_to: 1900,
    less_than_or_equal_to: Date.today.year
  }
  validates_uniqueness_of :student_id, {scope: [:course_id, :year], message: "already enrolled on selected course and year."}
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: %i[show edit update destroy]
  before_action :verify_authentication, only: %i[index show]
  before_action :verify_admin, except: %i[index show]

  def index
    if current_admin
      @enrollments = Enrollment.includes(:student, :course).all
    else
      @enrollments = Enrollment.includes(:student, :course).where(student_id: current_student.id)
    end
    @enrollments = @enrollments.order(year: :desc)
  end

  def new
    @enrollment = Enrollment.new
  end

  def create
    @enrollment = Enrollment.new(enrollment_params)

    respond_to do |format|
      if @enrollment.save
        EnrollmentMailer.with(enrollment: @enrollment).new_enrollment.deliver_later
        format.html { redirect_to enrollments_url, notice: "Enrollment was successfully created." }
        format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to enrollments_url, notice: "Enrollment was successfully updated." }
        format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @enrollment.destroy!

    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: "Enrollment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  def set_enrollment
    @enrollment = Enrollment.includes(:student, :course).find(params[:id])
  end

  def enrollment_params
    params.require(:enrollment).permit(:student_id, :course_id, :year)
  end
end

app/views/enrollments/_enrollment-table.html.erb
<tr id="<%= dom_id enrollment %>">
  <%- if current_admin %>
  <td>
    <%= enrollment.student.fullname %>
  </td>
  <%- end %>
  <td>
    <%= enrollment.course.name %>
  </td>
  <td>
    <%= enrollment.year || Date.today.year%>
  </td>
  <td>
    <%= link_to "See enrollment details", enrollment, class: "pure-button" %>
  </td>
</tr>

app/views/enrollments/_enrollment.html.erb
<div id="<%= dom_id enrollment %>">
  <p>
    <strong>student:</strong>
    <%= enrollment.student.fullname %>
  </p>

  <p>
    <strong>course:</strong>
    <%= enrollment.course.name %>
  </p>

  <p>
    <strong>course's year:</strong>
    <%= enrollment.year %>
  </p>

  <h3>Grades</h3>
  <%- if enrollment.quarters.size > 0 %>
  <table class="pure-table pure-table-striped">
    <thead>
      <th>Quarter #</th>
      <th>Grade</th>
      <th>Status</th>
      <%- if current_admin %>
      <th>Actions</th>
      <%- end %>
    </thead>
    <tbody>
      <%- enrollment.quarters.each do |quarter| %>
      <tr>
        <td><%= quarter.quarter_number %></td>
        <td><%= quarter.grade%></td>
        <td><%= quarter.passed? ? "Passed" : "Failed" %></td>
        <%- if current_admin %>
        <td><%= link_to "Edit", edit_enrollment_quarter_path(enrollment_id: enrollment.id, id: quarter.id), class: "pure-button button-success" %></td>
        <%- end %>
      </tr>
      <%- end %>
    </tbody>
  </table>
  <%- else %>
  <p>Your grades are missing in the space/time... (You don't have any yet)</p>
  <%- end%>

</div>

app/views/enrollments/_form.html.erb
<%= form_with(model: enrollment, class: "pure-form pure-form-stacked") do |form| %>
  <% if enrollment.errors.any? %>
    <div style="color: red">
      <h4><%= pluralize(enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h4>

      <ul>
        <% enrollment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <%= form.label "Student*", style: "display: block" %>
    <%= form.select :student_id,
      options_for_select(Student.active.pluck(:fullname, :id), { selected: enrollment.student_id })
    %>

    <%= form.label "Student*", style: "display: block" %>
    <%= form.select :course_id,
      options_for_select(Course.active.pluck(:name, :id), { selected: enrollment.course_id })
    %>

    <%= form.label "Select course year", style: "display: block" %>
    <%= form.select :year,
      options_for_select(
        ((Date.today.year - 6)..Date.today.year).to_a.reverse.collect{|year| [year, year]},
        { selected: enrollment.year || Date.today.year }
      )
    %>
    <span class="pure-form-message">* Required fields</span>
    <%= form.submit "Send", class: "pure-button pure-button-primary" %>
  </fieldset>
<% end %>

app/views/enrollments/edit.html.erb
<h1>Edit Enrollment</h1>

<%= render "form", enrollment: @enrollment, courses: @courses, students: @students %>

<br>

<div>
  <%= link_to "Back to Enrollments", enrollments_path, class: "pure-button" %>
</div>

app/views/enrollments/index.html.erb
<h1>Enrollments<%= " of #{current_student.fullname.titleize}" if current_student %></h1>

<div id="enrollments">
  <%- if @enrollments.length > 0 %>
    <table class="pure-table pure-table-striped">
      <thead>
        <tr>
          <%- if current_admin %>
          <th>Student</th>
          <%- end %>
          <th>Course</th>
          <th>Course's Year</th>
          <th>Actions</th>
        </tr>  
      </thead>
    <%- @enrollments.each do |enrollment| %>
      <%= render 'enrollment-table', enrollment: enrollment %>
    <%- end %>
    </table>
  <%- else %>
    <p>You don't have any enrollments, please referer to a Admin to solve it as soon as possible.</p>
  <%- end %>
</div>

<%= link_to("New enrollment", new_enrollment_path, class: "pure-button button-secondary") if current_admin %>

app/views/enrollments/new.html.erb
<h1>New Enrollment</h1>

<%= render "form", enrollment: @enrollment, courses: @courses, students: @students %>

<br>

<div>
  <%= link_to "Back to Enrollments", enrollments_path, class: "pure-button button-cancel" %>
</div>

app/views/enrollments/show.html.erb
<%= render @enrollment %>

<%- if current_student %>
<p>If you have any question about this enrollment, please contact to your admin.</p>
<%- end %>

<div class="pure-g">
  <%= link_to "Edit this enrollment", edit_enrollment_path(@enrollment), class: "pure-button pure-button-primary" if current_admin %>
  <%= link_to "Add grade to this enrollment", new_enrollment_quarter_path(enrollment_id: @enrollment.id), class: "pure-button button-secondary" if current_admin %>
  <%= button_to "Unenroll", @enrollment, method: :delete, class: "pure-button button-error", data: { turbo_confirm: "Are you sure?" } if current_admin %>

  <%= link_to "Back to enrollment", enrollments_path, class: "pure-button button-cancel" %>
</div>